# Generated by Django 5.1.15 on 2026-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning', '0002_bcd_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='hucontentitem',
            new_name='scanning_hu_session_7cff88_idx',
            old_name='scanning_hu_session_ser_idx',
        ),
        migrations.RenameIndex(
            model_name='hucontentitem',
            new_name='scanning_hu_ean_cod_4b771d_idx',
            old_name='scanning_hu_ean_idx',
        ),
        migrations.RenameIndex(
            model_name='hucontentitem',
            new_name='scanning_hu_manufac_0a25ea_idx',
            old_name='scanning_hu_mfr_idx',
        ),
        migrations.RenameIndex(
            model_name='scanlog',
            new_name='scanning_sc_session_e8ed3e_idx',
            old_name='scanning_log_sess_evt_idx',
        ),
        migrations.RenameIndex(
            model_name='scansession',
            new_name='scanning_sc_hu_numb_60916f_idx',
            old_name='scanning_sc_hu_numb_idx',
        ),
        migrations.RenameIndex(
            model_name='scansession',
            new_name='scanning_sc_status_bf55d6_idx',
            old_name='scanning_sc_status__idx',
        ),
        migrations.RenameIndex(
            model_name='serialnumberscan',
            new_name='scanning_se_session_6b2191_idx',
            old_name='scanning_sn_sess_valid_idx',
        ),
        migrations.RenameIndex(
            model_name='serialnumberscan',
            new_name='scanning_se_scanned_ca9cea_idx',
            old_name='scanning_sn_serial_idx',
        ),
        migrations.AlterField(
            model_name='scansession',
            name='pending_item_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialnumberscan',
            name='duplicate_scope',
            field=models.CharField(blank=True, default='none', max_length=16),
        ),
    ]
